on: push
name: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run dist
      - uses: actions/upload-artifact@master
        if: github.event.action == 'published'
        with:
          name: dist
          path: dist
