on: release
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Setup node (npmjs.org)
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run dist
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
